version: '2'
services:
    wordpress:
        build:
            context: ./
            dockerfile: ./Dockerfile
        links:
            - db:mysql
            - mailhog
        ports:
            - 80:80
        domainname: env.localhost
        hostname: env
        volumes:
            - ./public:/var/www/html
            - ./wp.sh:/var/www/html/wp.sh
            - ./phpconf.ini:/usr/local/etc/php/conf.d/phpconf.ini
        environment:
            WORDPRESS_DB_PASSWORD: docker
        depends_on:
            - mailhog
            - db

    mailhog:
        image: mailhog/mailhog
        ports:
            - 1025:1025
            - 8025:8025

    wpcli:
        image: tatemz/wp-cli
        volumes_from:
            - wordpress
        links:
            - db:mysql
        command: "sh wp.sh"

    db:
        image: mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: docker
